### ISSUE TITLE
run php artisan ide-helper:generate

### ISSUE THREAD

**Issue by AlehDev** [ConsoleTVs/Charts#34]
Hello,

console: run php artisan ide-helper:generate
Exception: Facade does not implement getFacadeAccessor method.
Skipping \ConsoleTVs\Charts\Charts.
A new helper file was written to _ide_helper.php

**Comment by ConsoleTVs** [comment]
php artisan ide-helper:generate

What is this?

**Comment by AlehDev** [comment]
https://github.com/barryvdh/laravel-ide-helper

**Comment by ConsoleTVs** [comment]
Probably due the fact that for an unknown reason i can't documentate that eaither manually with PhPDoc

**Comment by Arsfiqball** [comment]
> Exception: Facade does not implement getFacadeAccessor method.

I ever got similar error, but it because I still using Charts::new that has replaced by Charts::create.

**Comment by ConsoleTVs** [comment]
This replacement was made to fix older versions of php, as 'new' it's a reserved word

**Comment by AlehDev** [comment]
I think that the problem here: config/app.php
'Charts' => ConsoleTVs\Charts\Charts::class
Laravel docs:
How Facades Work
https://laravel.com/docs/5.3/facades#how-facades-work

**Comment by ConsoleTVs** [comment]
I'll take a look at it at the end of the week because I'm currently under exams, thanks for the issue!

**Comment by ConsoleTVs** [comment]
Probably fixed by @faustbrian !

**Comment by Kovah** [comment]
Was the fix (whichever it is) already released? Still have the same problem.

**Comment by faustbrian** [comment]
Will be fixed when `3.0.0` gets released. I am finishing up my last PR and then it should be ready.
